### ISSUE TITLE
name.zip not available

### ISSUE THREAD

**Issue by hvthaibk** [DexterZeng/EntMatcher#1]
Hello,
Thanks for sharing the code and datasets. Congratulations for your interesting work.
However, I could not find the link to download `name.zip` that you've mentioned [here](https://github.com/DexterZeng/EntMatcher#dataset-usage).
Could you please double check?
Thank you!

**Comment by DexterZeng** [comment]
Hi, thanks for your interest!
Can you try this link? https://1drv.ms/u/s!Ar-uYoG1mfiLkyMzDr_2ZgVM8WaD?e=IBZecN

**Comment by hvthaibk** [comment]
Thanks!
