### ISSUE TITLE
Bug in loadfile() function?

### ISSUE THREAD

**Issue by hvthaibk** [DexterZeng/EntMatcher#3]
Hello,
There might be a small bug in the `data.loadfile()` function which might impact training and evaluation of results.
For example, 
```
file_name = "./EntMatcher/data/SRPRS/en_fr_15k_V1/ref_ent_ids"
gt_pairs = loadfile(file_name)

ids_l = [id_l for id_l, _ in gt_pairs]
ids_r = [id_r for _, id_r in gt_pairs]
print(set(ids_l).intersection(set(ids_r)))
```

This code produces `{2099}` while an empty set `{}`  is expected. The issue might be from the following line. Maybe `[:-1]` should be removed?
```
th = line[:-1].split("\t")
```

Please double check since this may impact the benchmarking results. Thanks!

**Comment by DexterZeng** [comment]
Thanks a lot for pointing this out! We have made corresponding modification.
